### ISSUE TITLE
Client 1 fail to send message

### ISSUE THREAD

**Issue by Kagesss** [Ling2000/project-base-on-LWE-CS419-#1]
I have tried your program 7 times. In 6 of them, client1 fails to send any text to client2, and we got the error message on client1 and server. (see attached below). However, there is one time the program works for whatever reason, but it fails at the next try. 

two tries on my partner's computer
two tries on the ilab
three tries on my computer. The second try succeed, so I made a third try

[error on client.txt](https://github.com/Ling2000/project-base-on-LWE-CS419-/files/7647458/error.on.client.txt)
[error on server.txt](https://github.com/Ling2000/project-base-on-LWE-CS419-/files/7647459/error.on.server.txt)

**Comment by Ling2000** [comment]
Hi, It cannot run in the ilab because ilab has a different version of python and is without the key package to run it.
What thing did you input in the chat when you test? Because the feedback that you give shows that the server may not work normally.

**Comment by Kagesss** [comment]
This is what I get when I try to send the word "test" from client 1 to client 2. The left terminal is client.py, the middle one is server,py, the right one is client2.py

All I did was just type in "test" and click send button

<img width="1437" alt="Screen Shot 2021-12-03 at 3 30 58 AM" src="https://user-images.githubusercontent.com/37253847/144570757-716430fc-d195-4f3a-ad90-fb844f3a1b08.png">

**Comment by Kagesss** [comment]
And as you can see, the text was not sent

**Comment by Ling2000** [comment]
I see. it is strange. Because the same content can work normally on my computer. Almost all the send fail on your computer...

**Comment by Ling2000** [comment]
I show how I run my program in the last one minute of https://youtu.be/oy6mA-Y86sE. I don't know why this cannot run normally on your computer. The only thing that I can do is show you how it works on my computer. _(:зゝ∠)_

**Comment by Ling2000** [comment]
I think we may need to call the professor to judge because I cannot reimplement this problem _(:зゝ∠)_.

**Comment by symxmyz233** [comment]
It is **not actually a bug**, I think.
